nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  "@prisma/studio-core@*":
    peerDependenciesMeta:
      react:
        optional: true
      react-dom:
        optional: true
      "@types/react":
        optional: true
      "@types/react-dom":
        optional: true
  
  "inversify@*":
    dependencies:
      reflect-metadata: "*"

  "@inversifyjs/core@*":
    dependencies:
      reflect-metadata: "*"
